services:

  postgres_b:
    image: postgres:latest
    container_name: "postgres_b"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - "5632:5432"
    volumes:
      - ./conf/postgres_b/shards.sql:/docker-entrypoint-initdb.d/start.sql

  postgres_b1:
    image: postgres:latest
    container_name: "postgres_b1"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - "5633:5432"
    volumes:
      - ./conf/postgres_b1/shards.sql:/docker-entrypoint-initdb.d/start.sql

  postgres_b2:
    image: postgres:latest
    container_name: "postgres_b2"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - "5634:5432"
    volumes:
      - ./conf/postgres_b2/shards.sql:/docker-entrypoint-initdb.d/start.sql

  postgres_b3:
    image: postgres:latest
    container_name: "postgres_b3"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - "5635:5432"
    volumes:
      - ./conf/postgres_b3/shards.sql:/docker-entrypoint-initdb.d/start.sql
